config/routes.rb
Firebird::Application.routes.draw do

  get "home/index"
  root :to => "home#index" 

  resources :referee_requests, :only => [:index, :create, :new]
  resources :check_requests, :only => [:index, :create, :new]
  resources :free_agents, :only => [:index, :create, :new]

end

app/models/check_request.rb
class CheckRequest
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :first, :last, :email, :phone_number, :team_name, :team_level, :date_needed, :team_expense, :amount, :payable_to, :delivery_method, :mailing_address

  validates_presence_of :first, :last, :email, :phone_number, :team_name, :team_level, :date_needed, :team_expense, :amount, :payable_to, :delivery_method
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/free_agent.rb
class FreeAgent
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  POSITIONS = %w[Forward Defense Goaltender]
  PROGRAMS = %w[A B C D Over-30 Adult-Hockey-Skills Adult-Rookie-Class Dynamic-Skills]
  SKILL_LEVEL = %w[Advanced Intermediate Novice Beginner]
  LEVELS_PLAYED = [ 'Never played competitively, just pond hockey',
                    'Never played or skated until recently',
                    'Youth house league',
                    'Youth travel A/B hockey', 
                    'Youth travel tier 1 or tier 2',
                    'High School',
                    'Junior B/ Junior A tier 2 or 3',
                    'Junior A tier 1/ Major Junior',
                    'ACHA D2 or D3',
                    'ACHA D1/ NCAA D3',
                    'NCAA D1/ Minor Pro/ Euro Pro/ NHL' ]
  GOALS = [ 'Learn how to skate and play hockey',
            'Improve skills to transition from beginner to novice',
            'Improve skills to transition from novice to intermediate',
            'Play in the best and most competitive league that is suitable to my skill level',
            'Join a team and enjoy the camaraderie and exercise' ]
  
  def self.POSITIONS
    POSITIONS
  end
  
  def self.PROGRAMS
    PROGRAMS.collect{ |p| p.humanize }
  end
  
  def self.SKILL_LEVEL
    SKILL_LEVEL.collect{ |s| s.humanize }
  end
  
  def self.LEVELS_PLAYED
    LEVELS_PLAYED
  end
  
  def self.GOALS
    GOALS
  end  
  
  
  
  attr_accessor :name, :email, :date_of_birth, :phone_number, :position, :programs, :skill_level, :highest_level_played, :last_competitive_team, :last_adult_league_team, :goals

  validates_presence_of :name, :email, :date_of_birth, :phone_number, :position, :skill_level, :highest_level_played, :last_competitive_team, :last_adult_league_team
  validates_date :date_of_birth
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  
end

app/models/referee_request.rb
class RefereeRequest
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :email, :team_name, :team_level, :game_date, :game_time, :game_location, :on_ice_officials, :scorekeeper

  validates_presence_of :name, :email, :team_name, :team_level, :game_date, :game_time, :game_location, :on_ice_officials, :scorekeeper
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/referee_request_form.rb
class RefereeRequestForm
  include ActiveModel::Validations
  include ActiveModel::Conversation
  extend ActiveModel::Naming

  attr_accessor :name, :email

  validates_presence_of :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i


  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/check_requests_controller.rb
class CheckRequestsController < ApplicationController
  
  def index
  end

  def new
    @check_request = CheckRequest.new
  end

  def create
    @check_request = CheckRequest.new(params[:check_request])
    if @check_request.valid?
      Notifier.check_request(@check_request).deliver
      redirect_to check_requests_path, :notice => 'Check Request has been submitted'
    else
      render :action => "new"
    end
  end


end

app/controllers/free_agents_controller.rb
class FreeAgentsController < ApplicationController
  def index
  end

  def new
    @free_agent = FreeAgent.new
  end

  def create
    @free_agent = FreeAgent.new(params[:free_agent])
    if @free_agent.valid?
      Notifier.free_agent(@free_agent).deliver
      redirect_to free_agents_path, :notice => 'Free Agent Request has been submitted'
    else
      @free_agent.errors.each{|e| puts e}
      render :action => "new"
    end    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    redirect_to 'http://www.wshl.pointstreaksites.com/'
  end

end

app/controllers/referee_requests_controller.rb
class RefereeRequestsController < ApplicationController
  
  before_filter :set_location_options

  def index
  end

  def new
    @referee_request = RefereeRequest.new
  end

  def create
    @referee_request = RefereeRequest.new(params[:referee_request])
    if @referee_request.valid?
      Notifier.referee_request(@referee_request).deliver
      redirect_to referee_requests_path, :notice => 'Referee Request has been submitted'
    else
      render :action => "new"
    end
  end

  private

    def set_location_options
      @location_options = %w[oceanside_ice_arena arcadia_ice].collect{|x| x.humanize.titleize}
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/free_agents_helper.rb
module FreeAgentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/check_requests/index.html.erb
<p>
  <%= link_to 'New Check Request Form', new_check_request_path %>
</p>

app/views/check_requests/new.html.erb
<h3>New Check Request</h3>
<ul class="square">
  <li>Checks will be issued within 10 business days.</li>
  <li>Receipts must be  for verification.  Please email them to checkrequest@dyha.org after submitting the online form.</li>
  <li>Upon submittal you shall receive a confirmation email with further instructions.</li>
  <li>Be sure to complete each of the fields below accurately.</li> 
  <li>If you need assistance please email jacque.gomez@dyha.org</li>
</ul> 
<%= semantic_form_for @check_request do |form| %>
  <%= form.inputs do %>
    <%= form.input :first %>
	<%= form.input :last %>
    <%= form.input :email %>
    <%= form.input :phone_number %>
    <%= form.input :team_name %>
    <%= form.input :team_level %>
    <%= form.input :date_needed %>
    <%= form.input :team_expense, :as => :radio, :collection => %w{Yes No} %>
    <%= form.input :amount %>
    <%= form.input :payable_to %>
    <%= form.input :delivery_method, :as => :radio, :collection => ["Pick up at Oceanside", "Mail it please"] %>
    <%= form.input :mailing_address, :as => :text, :input_html => { :rows => 4, :style => 'width: 450px;' } %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>

app/views/free_agents/index.html.erb
<div class="row">
  <div class="span12">
    <%= link_to 'New Free Agent Request', new_free_agent_path, :class => 'btn' %>
  </div>
</div>

app/views/free_agents/new.html.erb
<br/>
<h3>Adult Hockey Inquiry</h3>
<br/>
<p>Oceanside is always accepting new participants for our adult hockey programs. If you would like more information about Adult Hockey at OIA please complete and submit the brief questionnaire below.  After submitting the form we will contact you at our earliest convenience to discuss next steps</p>
<%= simple_form_for @free_agent do |form| %>
    <%= form.input :name %>
    <%= form.input :email, :hint => 'So we can email you... we prefer this.'%>
    <%= form.input :phone_number, :input_html => { :class =>  'input-medium'}, :hint => 'So we can call you, in case email is not effective' %>
    <%= form.input :date_of_birth, :as => :string, :input_html => { :class =>  'input-medium'} %>
    <%= form.input :position, :as => :radio_buttons, :collection => FreeAgent.POSITIONS, :hint => 'Position that you prefer to play.' %>
    <%= form.input :programs, :label => 'Programs of Interest', :as => :check_boxes, :hint => 'Please check all that apply.', :collection => FreeAgent.PROGRAMS %>
    <%= form.input :skill_level, :as => :radio_buttons, :collection => FreeAgent.SKILL_LEVEL %>    
    <%= form.input :highest_level_played, :as => :radio_buttons, :collection => FreeAgent.LEVELS_PLAYED, :hint => 'Please be honest... we just want to place you where you are comfortable'%>
    <%= form.input :last_competitive_team %>
    <%= form.input :last_adult_league_team %>        
    <%= form.input :goals, :label => 'Your Goals', :as => :check_boxes, :hint => 'Please check all that apply.', :collection => FreeAgent.GOALS %>    
    <div class="form-actions">
      <%= form.button :submit, 'Submit Form' %>
    </div>
<% end %>

app/views/home/index.html.erb
<h1>DYHA Toolbox</h1>
<ul>
	<li><%= link_to 'Referee Requests', referee_requests_path %></li>	
	<li><%= link_to 'Check Requests', check_requests_path %></li>
</ul>
<h1>OAHL Toolbox</h1>
<ul>
	<li><%= link_to 'Free Agents', free_agents_path %></li>	
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firebird</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="container">
    <div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, {:id => "flash_#{name}", :class => "alert alert-#{name}"} %>
      <% end %>
    </div>

    <%= yield %>
    
  </div>

</body>
</html>

app/views/notifier/check_request.text.erb
--------------------------------------------------------
Check Request - <%= @key %>
--------------------------------------------------------

Reference Id: <%= @key %>
Submitted By: <%= @request.first %> <%= @request.last %>
Reply To: <%= @request.email %>
Phone: <%= @request.phone_number %>

Team Name: <%= @request.team_name %>
Team Level: <%= @request.team_level %>

Date Needed: <%= @request.date_needed %>
Team Expense?: <%= @request.team_expense %>
Amount: <%= @request.amount %>
Payable To: <%= @request.payable_to %>

Delivery Method: <%= @request.delivery_method %>
Mailing Address:
<%= @request.mailing_address %>

--------------------------------------------------------
This request has been submitted online at dyha.org
--------------------------------------------------------

app/views/notifier/check_request_confirmation.text.erb
Hello <%= @request.first %>,

We have received your submission of the DYHA Check Request form.  Here are a few important reminders about the Check Request process:

- Checks will be issued within 10 business days.
- Receipts must accompany each check request for verification.

Receipts may be submitted online via email or by delivering a copy to the DYHA office at the arena.  Your mobile phone camera is a quick and easy way to capture a receipt image that can sent via email.  

Receipts should be submitted to checkrequest@dyha.org.  For most-efficient processing we request that email receipts be submitted with your Reference Id of <%= @key %> in the subject line.

Thank You,

DYHA Online Services

--------------------------------------------------------
Check Request - <%= @key %>
--------------------------------------------------------

Reference Id: <%= @key %>
Submitted By: <%= @request.first %> <%= @request.last %>
Reply To: <%= @request.email %>
Phone: <%= @request.phone_number %>

Team Name: <%= @request.team_name %>
Team Level: <%= @request.team_level %>

Date Needed: <%= @request.date_needed %>
Team Expense?: <%= @request.team_expense %>
Amount: <%= @request.amount %>
Payable To: <%= @request.payable_to %>

Delivery Method: <%= @request.delivery_method %>
Mailing Address:
<%= @request.mailing_address %>

--------------------------------------------------------
This request has been submitted online at dyha.org
--------------------------------------------------------

app/views/notifier/free_agent.text.erb
--------------------------------------------------------
Free Agent Request
--------------------------------------------------------

Submitted By: <%= @request.name %>
Reply To: <%= @request.email %>
Phone: <%= @request.phone_number %>
DOB: <%= @request.date_of_birth %>

Position: <%= @request.position %>
Highest Level Played: <%= @request.highest_level_played %>
Skill Level: <%= @request.skill_level %>
Last Competitive Team: <%= @request.last_competitive_team %>
Last Adult League Team: <%= @request.last_adult_league_team %>
Programs Interested: <%= @request.programs.join(', ') %>  
Goals: <%= @request.goals.join(', ') %>  

--------------------------------------------------------
Submitted online at oceansideicearena.net
--------------------------------------------------------

app/views/notifier/free_agent_request.text.erb
--------------------------------------------------------
Free Agent Request
--------------------------------------------------------

Submitted By: <%= @request.name %>
Reply To: <a mailto:"<%= @request.email %>"><%= @request.email %></a>
Phone: <%= @request.phone%>

Position: <%= @request.position %>
Evaluation: <%= @request.evaluation_session %>

Hockey Bio: 

<%= @request.game_date %>

--------------------------------------------------------
Submitted online at oceansideicearena.net
--------------------------------------------------------

app/views/notifier/referee_request.text.erb
Reference Id: <%= @key %>
Submitted By: <%= @request.name %>
Reply To: <%= @request.email %>

Team Name: <%= @request.team_name %>
Team Level: <%= @request.team_level %>

Game Date: <%= @request.game_date %>
Game Time: <%= @request.game_time %>
Game Location: <%= @request.game_location %>

Number Of On-Ice Officials: <%= @request.on_ice_officials %>
Needs Scorekeeper?: <%= @request.scorekeeper %>

--------------------------------------------------
This request has been submitted online at dyha.org

PLEASE DO NOT REPLY DIRECTLY TO THIS MESSAGE
--------------------------------------------------

app/views/referee_requests/index.html.erb
<p>
  <%= link_to 'New Referee Request Form', new_referee_request_path %>
</p>

app/views/referee_requests/new.html.erb
<h3>New Referee Request</h3>
<ul class="square">
  <li>A separate referee request must be made for each game you are scheduling.</li>
  <li>Be sure to complete each of the fields below accurately.</li> 
  <li>You will receive an emailed response within 48 hours from the Phoenix Ice Hockey Referees Association with a confirmation of your scheduled game.</li>
  <li>If you need immediate assistance please email refs@dyha.org.</li>
</ul> 
<%= semantic_form_for @referee_request do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :email %>
    <%= form.input :team_name %>
    <%= form.input :team_level %>
    <%= form.input :game_date %>
    <%= form.input :game_time %>
    <%= form.input :game_location, :as => :radio, :collection => @location_options %>
    <%= form.input :on_ice_officials, :as => :radio, :collection => %w[2 3 4], :label => "Number of on-ice officials needed" %>
    <%= form.input :scorekeeper, :as => :radio, :collection => %w[Yes No], :label => "I need a scorekeeper" %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>